version: "3.7"
services:
  mongo:
    image: mongo:3.6.8
    env_file:
      ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_AUTH_DATABASE_NAME}
    container_name: ${MONGODB_CONTAINER_NAME}
    ports:
      - '${MONGODB_PORT}:27017'